import {
  // EoiBreadcrumb,
  // EoiEditor,
  // EoiFileView,
  // EOIHeader,
  // EoiHeaderSearch,
  // EoiIframeView,
  // EoiLastingSearch,
  // EOILoginControl,
  // EOINavControl,
  // EoiRouterTabs,
  // EOISidNavigation,
  // EoiSvgIcon,
  // EoiTableHeader,
  // EoiTableView,
  // EoiTableViewV2,
  // EOIUserControl,
  EOIFormFieldView,
  EOITab,
} from '@eoi-plus/components';
import { withAllInstall } from '@eoi-plus/utils';

// export default withAllInstall([
//   EOIHeader,
//   EOIUserControl,
//   EOISidNavigation,
//   EOINavControl,
//   EOILoginControl,
//   EoiHeaderSearch,
//   EoiRouterTabs,
//   EoiTableHeader,
//   EoiTableView,
//   EoiTableViewV2,
//   EoiFileView,
//   EoiEditor,
//   EoiBreadcrumb,
//   EoiLastingSearch,
//   EoiSvgIcon,
//   EoiIframeView,
// ]);

export default {
  // EoiBreadcrumb,
  // EoiEditor,
  // EoiFileView,
  // EOIHeader,
  // EoiHeaderSearch,
  // EoiIframeView,
  // EoiLastingSearch,
  // EOILoginControl,
  // EOINavControl,
  // EoiRouterTabs,
  // EOISidNavigation,
  // EoiSvgIcon,
  // EoiTableHeader,
  // EoiTableView,
  // EoiTableViewV2,
  // EOIUserControl,
  EOIFormFieldView,
  EOITab,
}
